# Generated by Django 3.0.8 on 2021-05-29 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_remove_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
